sudo: false
language: python

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.5
      env: TOXENV=py35-django21
    - python: 3.6
      env: TOXENV=py36-django21

install:
  - python setup.py develop
  - pip install tox

script:
  - tox
